###
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Leonardo",
  "email": "Leonardocbizerra@gmail.com",
  "senha": "0304Leonardo",
  "tipo": "ADMIN",
  "documento": "075.946.869-93",
  "logradouro": "Av. Guedner",
  "numero": "1321",
  "bairro": "Aclimação",
  "cidade": "Maringá",
  "estado": "Paraná",
  "cep": "87050-390",
  "celular": "(41)9 9741-4130"
}

###


POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "Leonardocbizerra@gmail.com",
  "senha": "0304Leonardo"
}

###

GET localhost:8080/usuarios
Authorization: Bearer {{$auth.token("")}}
###

GET localhost:8080/usuarios/{{id}}
Authorization: Bearer {{$auth.token("")}}
###

PUT localhost:8080/usuarios/{{id}}
Authorization: Bearer {{$auth.token("")}}
Content-Type: application/json

{
    "nome": "",
    "email": "",
    "senha": "",
    "tipo": "",
    "documento": ""
}


###

DELETE localhost:8080/usuarios/{{id}}
Authorization: Bearer {{$auth.token("")}}

###

GET http://localhost:8080/alimentos
Authorization: Bearer {{$auth.token("")}}

###

GET http://localhost:8080/alimentos/{{id}}
Authorization: Bearer {{$auth.token("")}}

###

POST http://localhost:8080/alimentos
Authorization: Bearer {{$auth.token("")}}
Content-Type: application/json

{
  "nome":"",
  "descricao": "",
  "validade": "",
  "quantidade": "",
  "categoriaId": "",
  "status": ""
}

###

PUT http://localhost:8080/alimentos/{{id}}
Authorization: Bearer {{$auth.token("")}}
Content-Type: application/json

{
  "nome":"",
  "descricao": "",
  "validade": "",
  "quantidade": "",
  "categoriaId": "",
  "status": ""
}


###
GET http://localhost:8080/categorias
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodW5nZXJsZXNzLWFwaSIsInN1YiI6Ikxlb25hcmRvY2JpemVycmFAZ21haWwuY29tIiwiZXhwIjoxNzYyNjc0MzI0fQ.gqvEWE08kxfZ46jki_oQOkvPVFWH0EgwXPoRnFWzYWo

###
POST http://localhost:8080/alimentos
Authorization: Bearer
Content-Type: application/json

{

}